### ISSUE TITLE
Keep getting error while trying to use locale in typescript.

### ISSUE THREAD

**Issue by 0xorial** [js-joda/js-joda#364] opened 2019-11-10 23:07 UTC
I get the following error:
```
Module not found: Error: Can't resolve 'js-joda' in 'node_modules\@js-joda\locale_en-us\dist'
```
Could someone let me know in which direction should I be looking to fix it?

**Comment by phueper** [comment] 2019-11-16 16:44
Hi @0xorial 

i'm sorry, since i'm not using typescript, i really can't be of much help... 

Maybe adding a code sample  that helps reproducing the problem might help ? 

Regards, Pattrick

**Comment by phueper** [comment] 2019-11-18 11:21
@0xorial could this be a duplicate of #366  ? Could you try the proposed workaround in that issue, please?

**Comment by phueper** [comment] 2019-11-23 13:05
We release @js-joda/locale 3.0.1 tagged as "latest" ... i hope this will resolve this issue, could you please try again? 

I'll close this issue, feel free to reopen, if your problem is not resolved by the new release.

Regards, Pattrick

**Closed by phueper** 2019-11-23 13:05 UTC
