### ISSUE TITLE
Bug interpreting times in the "overlap" period during fall DST change.

### ISSUE THREAD

**Issue by dcosson** [js-joda/js-joda#166] opened 2017-05-19 19:02 UTC
In testing out js-joda and comparing it to the java version, I noticed once bug. In the "overlap" period at a daylight savings boundary (e.g. fall in the US), there are two different offset values for the same time.

In the Java implementation, it works as expected:

```
jshell> import java.time.ZonedDateTime

jshell> ZonedDateTime.parse("2017-11-05T01:00:00-07:00[America/Los_Angeles]").toInstant().toString()
$2 ==> "2017-11-05T08:00:00Z"

jshell> ZonedDateTime.parse("2017-11-05T01:00:00-08:00[America/Los_Angeles]").toInstant().toString()
$3 ==> "2017-11-05T09:00:00Z"

jshell> ZonedDateTime.parse("2017-11-05T02:00:00-08:00[America/Los_Angeles]").toInstant().toString()
$4 ==> "2017-11-05T10:00:00Z"
```

js-joda interprets "2017-11-05T01:00:00-07:00[America/Los_Angeles]" as "2017-11-05T01:00:00-08:00[America/Los_Angeles]" which is actually a different time (it should be the second 1 am, i.e. it comes just after 1:59 am)

```
JSJoda.ZonedDateTime.parse("2017-11-05T01:00:00-07:00[America/Los_Angeles]").toInstant().toString()
"2017-11-05T08:00:00Z"
JSJoda.ZonedDateTime.parse("2017-11-05T01:00:00-08:00[America/Los_Angeles]").toInstant().toString()
"2017-11-05T08:00:00Z"
JSJoda.ZonedDateTime.parse("2017-11-05T02:00:00-08:00[America/Los_Angeles]").toInstant().toString()
"2017-11-05T10:00:00Z"
```

The spring doesn't have a problem in JSJoda.

Not sure if this bug belongs in js-joda or js-joda-timezone

**Comment by pithu** [comment] 2017-05-21 18:49
Hi, 

thx for reporting, 

looks like a bug in the DateTimeFormatter / ZoneId Parser in the js-joda core library.

I will have a lokk.

**Comment by pithu** [comment] 2017-05-25 14:10
Hi @dcosson 

I cant reproduce the issue, neither with the latest threeten backport nor the latest jdk 8 version [see groovy test script](https://gist.github.com/pithu/a37f481b257f34774faf3eaa75be7f2b). I get the same results as with js-joda (see the 2 commits above).

A look in the threeten code says that the offset is ignored if a zone id is supplied. In case of an overlap the earlier offset is used, typically corresponding to "summer". Basically its the same behavior as described here [LocalDateTime.atZone](https://docs.oracle.com/javase/8/docs/api/java/time/LocalDateTime.html#atZone-java.time.ZoneId-) 

What jdk version did you use for your jshell example ?

**Comment by dcosson** [comment] 2017-05-25 17:51
That's interesting I guess this bug (or maybe intentional behavior) goes pretty deep.

I tested it on the latest openjdk 9 version on docker hub, just because java 9 has jshell built-in. I ran it as: `docker run -it openjdk:9-b170-jdk jshell`

**Comment by dcosson** [comment] 2017-05-25 17:56
The line that made me think the version I'm seeing in jdk 9 is correct was in the [threeten docs ](http://www.threeten.org/threetenbp/apidocs/org/threeten/bp/ZonedDateTime.html)

It says "In an overlap there are local date-time values with two valid offsets." which makes me think that when passing in both offset and timezone (which is otherwise redundant outside of this 1 hour a year), the intention was to respect the offset if it is one of the two valid offsets within the timezone.

**Comment by pithu** [comment] 2017-05-26 16:34
Interesting: "jdk9 early access" behaves different then jdk8 and threeten. 

So i wouldn't call it a bug, but a different interpretation of an edge case. Probably your issue should go to the jdk team. The question is, why jdk9 changes the behavior for that case

**Comment by pithu** [comment] 2017-07-30 12:14
I forwarded the question to threeten backport project -> ThreeTen/threetenbp#73

**Comment by pithu** [comment] 2017-09-08 15:57
Its a bug in threeten backport and jdk8 and therefore in js-joda. its fixed in jdk9. 

The proposal is to prioritise the offset if zone and offset is present.

We will fix it in that way!

**Closed** 2017-09-21 07:15 UTC
Labels: bug
