### ISSUE TITLE
Writing js-joda in TypeScript

### ISSUE THREAD

**Issue by lundmikkel** [js-joda/js-joda#305] opened 2019-04-13 17:08 UTC
I know you already have type definitions in js-joda, but are there any plans to convert the whole library into TypeScript?

**Comment by benny-medflyt** [comment] 2019-09-25 20:12
This was discussed here: <https://github.com/js-joda/js-joda/issues/23#issuecomment-280443227>

**Comment by phueper** [comment] 2019-09-26 05:21
clsoing as duplicate of #23

**Closed by phueper** 2019-09-26 05:21 UTC
