### ISSUE TITLE
Question: YearMonth.with(number, number) is a js-joda extension? Must be documented?

### ISSUE THREAD

**Issue by InExtremaRes** [js-joda/js-joda#411] opened 2020-06-23 22:18 UTC
The tests for `YearMonth` use an overload of `with` using two numbers (year and month) but I can't find documentation for it, nor here nor in the threetenbp. Is this a js-joda extension? Should that be documented and declared in TS types?

https://github.com/js-joda/js-joda/blob/4098e8f8a9adbf67300bb95cb6fbf080b3ef827a/packages/core/test/YearMonthTest.js#L88-L112

**Comment by pithu** [comment] 2020-06-24 06:52
Interesting, looks like a bug or a "creative extension" of the threeten API. 

But IMO `YearMonth.with(number, number)` makes no sense and should be removed, it's a duplicate of `YearMonth.of(number, number)`. Could be a cleanup for a next major update.

**Comment by InExtremaRes** [comment] 2020-06-24 20:33
The only reason I can think for its existence is that `ym.with(number, number)` can avoid a new instance if the fields are the same. But I don't see a reason for it, `YearMonth` is not particularly expensive to create :thinking:.

Since I already started some breaking changes I'll send a PR removing it.

**Closed** 2020-06-26 05:29 UTC
