### ISSUE TITLE
JSJoda object is undefined in browser

### ISSUE THREAD

**Issue by leiqiao0** [js-joda/js-joda#156] opened 2017-04-25 10:35 UTC
When I using the v1.5 release dist/js-joda.js file was stuck, but minified version is ok.

**Comment by pithu** [comment] 2017-04-26 18:16
Hello @leiqiao0 

Thanks for using js-joda and for reporting. 

Can you describe your problem in more detail. I can't reproduce your issue. 

Importing in a html page, as in the example below, worx for me.

```
<html>
    <head>
        <script src="http://cdn.jsdelivr.net/js-joda/1.5.0/js-joda.js"></script>
        <script>
            console.log(JSJoda.LocalDateTime.now().toString());
        </script>
    </head>
    <body></body>
</html>
```

**Comment by leiqiao0** [comment] 2017-04-27 02:38
Below is the fragment of my JSP file:

```javascript
<script src="/js/app.core.js"></script>
<script>
    var LAST_COLLECT_TIME = '<fmt:formatDate value="${device.latest_collect_time}" pattern="yyyy-MM-dd"/>';
</script>
<script src="/js/time/js-joda.js"></script>
<script src="/js/adm.device.detail.js"></script>
</body>
</html>
```
It's strange, when this page has loaded, no errors in the console, but JSJoda object still not found.

**Comment by leiqiao0** [comment] 2017-04-27 02:56
```javascript
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		define([], factory);
	else if(typeof exports === 'object')
		exports["JSJoda"] = factory();
	else {
                console.log('boom');
		root["JSJoda"] = factory();
        }
```
no 'boom'  in the console when loaded.

**Comment by phueper** [comment] 2017-04-27 05:13
Hi @leiqiao0,

maybe the JS Files (app.core.js) loaded before joda define one of the module loading interfaces? e.g. define oder module.exports? In that case the joda file will use that instead of defining JSJoda global object... That would explain why the console.log does not happen... could you try moving the js-joda loading before the other files?
If that helps you could either leave it there or try using your apps module loading (i.e. require or import js-joda.js?)

Regards, Pattrick

**Comment by leiqiao0** [comment] 2017-04-27 05:15
@phueper Thanks for your explaination.

**Comment by phueper** [comment] 2017-04-27 05:31
@leiqiao0 does that mean it solved your issue? Could you close this issue then, please? 

Also.. just as a "warning" ... in v1.5.2 we switched the loading mechanism of the minified version to the umd logic as well (https://github.com/js-joda/js-joda/blob/master/CHANGELOG.md) ... so it will have the same beavior as the non-minified file.

**Closed** 2017-04-27 06:10 UTC
