### ISSUE TITLE
Can we add documentation for JsJoda alternatives to startOf("day")

### ISSUE THREAD

**Issue by dgreene1** [js-joda/js-joda#306] opened 2019-04-15 15:18 UTC
Many people coming to this library were previously using MomentJS and Luxon. And in those libraries, it's very common to utilize `moment().startOf("day")`. I think it would be great to have some kind of documentation to help those coming from MomentJS or Luxon to quickly be able to utilize the correct API method.

I've done my best to document what I believe the options are in [this StackOverflow answer](https://stackoverflow.com/a/54351942/706768) (which I would appreciate some upvotes on haha). But jokes aside, I'd appreciate:
* some input on [that answer](https://stackoverflow.com/a/54351942/706768)
* direction on where I could PR the `js-joda` documentation so that the website had a clear answer on how to get the start of the time for a given ZonedDateTime

Here's what I have so far: https://stackoverflow.com/a/54351942/706768

**Comment by alamothe** [comment] 2019-05-26 07:42
startOfDay = zonedDateTime
        .truncatedTo(ChronoUnit.DAYS)

    startOfWeek = zonedDateTime
        .with(TemporalAdjusters.previousOrSame(DayOfWeek.SUNDAY))
        .truncatedTo(ChronoUnit.DAYS)

Also note:

- While moment has only a single `moment`, `js-joda` has `LocalDate`, `LocalTime`, `LocalDateTime`, `ZonedDateTime` and `Instant`. Many of concepts don't apply to each. For example, `LocalDate` is only a date, and does not contain time at all, so start of day is meaningless for it. `Instant` does not have a timezone, so no start of day cannot be defined without a timezone.

**Comment by iraycd** [comment] 2020-03-09 11:47
https://js-joda.github.io/js-joda/manual/ZonedDateTime.html

```js

// create from a LocalDate(Time) (requires `js-joda-timezone`)
LocalDate.parse("2012-06-06")
  .atStartOfDay()
  .atZone(ZoneId.of("Europe/Paris")); // 2012-06-06T00:00+02:00[Europe/Paris]
ZonedDateTime.of(
  LocalDateTime.parse("2012-06-06T00:00"),
  ZoneId.of("Europe/Paris")
); // 2012-06-06T00:00+02:00[Europe/Paris]
ZonedDateTime.of(
  LocalDate.parse("2012-06-06"),
  LocalTime.MIDNIGHT,
  ZoneId.of("Europe/Paris")
); // 2012-06-06T00:00+02:00[Europe/Paris]
```

**Comment by pithu** [comment] 2020-07-03 07:42
Looks like the issue is solved, i will close it for now.

And please note: js-joda is NOT a port of Jodatime but of the threeten API.

**Closed by pithu** 2020-07-03 07:42 UTC
