### ISSUE TITLE
IllegalArgumentException: Unknown pattern letter: d

### ISSUE THREAD

**Issue by steve-taylor** [js-joda/js-joda#136] opened 2017-02-21 10:48 UTC
Using js-joda 1.3.0

```
import {DateTimeFormatter} from 'js-joda/src/format/DateTimeFormatter';
import {LocalDate} from 'js-joda/src/LocalDate';

const dateFormatter = DateTimeFormatter.ofPattern('d MM yyyy');
```

Result:

```
    IllegalArgumentException: Unknown pattern letter: d
      
      at DateTimeFormatterBuilder._parsePattern (node_modules/js-joda/src/format/DateTimeFormatterBuilder.js:2145:1532)
      at DateTimeFormatterBuilder.appendPattern (node_modules/js-joda/src/format/DateTimeFormatterBuilder.js:2130:159)
      at Function.ofPattern (node_modules/js-joda/src/format/DateTimeFormatter.js:808:363)
      at Object.<anonymous> (src/pages/about-you/Validator.js:20:424)
      at Object.<anonymous> (src/pages/about-you/Validator.spec.js:2:44)
```

This is the exact pattern specified in the JSDoc, but it explodes.

**Comment by phueper** [comment] 2017-02-21 10:57
Hi @steve-taylor 

thanks for reporting, i will have a look at this

Regards, Pattrick

**Comment by phueper** [comment] 2017-02-21 10:57
Could you try with `dd MM yyyy` as a workaround for now?

**Comment by steve-taylor** [comment] 2017-02-21 11:03
Thanks for the quick response. It still fails with `dd`.

**Comment by steve-taylor** [comment] 2017-02-21 11:12
In `DateTimeFormatterBuilder`:

```js
    _parsePattern(pattern) {
        /** Map of letters to fields. */
        const FIELD_MAP = {
            'G': ChronoField.ERA,
            'y': ChronoField.YEAR_OF_ERA,
            'u': ChronoField.YEAR,
            'Q': IsoFields.QUARTER_OF_YEAR,
            'q': IsoFields.QUARTER_OF_YEAR,
            'M': ChronoField.MONTH_OF_YEAR,
            'L': ChronoField.MONTH_OF_YEAR,
            'D': ChronoField.DAY_OF_YEAR,
            'd': ChronoField.DAY_OF_MONTH,
            'F': ChronoField.ALIGNED_DAY_OF_WEEK_IN_MONTH,
            'E': ChronoField.DAY_OF_WEEK,
            'c': ChronoField.DAY_OF_WEEK,
            'e': ChronoField.DAY_OF_WEEK,
            'a': ChronoField.AMPM_OF_DAY,
            'H': ChronoField.HOUR_OF_DAY,
            'k': ChronoField.CLOCK_HOUR_OF_DAY,
            'K': ChronoField.HOUR_OF_AMPM,
            'h': ChronoField.CLOCK_HOUR_OF_AMPM,
            'm': ChronoField.MINUTE_OF_HOUR,
            's': ChronoField.SECOND_OF_MINUTE,
            'S': ChronoField.NANO_OF_SECOND,
            'A': ChronoField.MILLI_OF_DAY,
            'n': ChronoField.NANO_OF_SECOND,
            'N': ChronoField.NANO_OF_DAY
        };
```

In the debugger, all values in `FIELD_MAP` are undefined. This is both in Node 6.2.2 and Chrome. I wonder if this has to do with Webpack (for my browser usage of the code) and Jest (for testing) deal with the imports.

Relevant Webpack 2 config section:

```js
resolve: {
  modules: [
    path.resolve(__dirname, './node_modules'),
    path.resolve(__dirname, './lib'),
  ],
  extensions: ['.js', '.json', '.scss', 'png', 'jpg', 'gif', '.svg'],
},
```

Jest config (in package.json):

```json
  "jest": {
    "moduleNameMapper": {
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/__mocks__/fileMock.js",
      "\\.(css|scss|sass)$": "<rootDir>/__mocks__/styleMock.js"
    },
    "transformIgnorePatterns": [
      "<rootDir>/node_modules/(?!js-joda)/"
    ]
  },
```

**Comment by phueper** [comment] 2017-02-21 11:28
Hi @steve-taylor 

maybe the problem is that you are requiring/importing the src files from js-joda instead of the js-joda package... since our src files are written in ES6 it is possible that you will need to use babel for that to work... could you try doing this: 

```import { DateTimeFormatter, LocalDate } from 'js-joda';

const dateFormatter = DateTimeFormatter.ofPattern('d MM yyyy');

const date = LocalDate.now();

console.log(dateFormatter.format(date));```

when i tried that with `babel-node` everything seemed to work... and if i translated it using `babel` it also worked in plain `node` 

Regards, Pattrick

**Comment by steve-taylor** [comment] 2017-02-21 11:29
I changed the import from this:

```js
import {DateTimeFormatter} from 'js-joda/src/format/DateTimeFormatter';
import {LocalDate} from 'js-joda/src/LocalDate';
```

to this:

```
import {DateTimeFormatter} from 'js-joda';
import {LocalDate} from 'js-joda';
```

and now it works.

I was importing directly from the source for two reasons:
1. To reduce the bundle size when Webpack's tree shaking is fixed (currently completely broken); and
2. To get code completion in WebStorm.

The first reason is reasonably important. The second reason is mitigated by the type definition file which I just found in the dist directory.

This doesn't look like a js-joda bug, so I'm happy to close it.

**Comment by phueper** [comment] 2017-02-21 11:30
Hehe... see my above comment... i'm glad that it works now for you... closing this :)

**Comment by steve-taylor** [comment] 2017-02-21 11:30
> when i tried that with `babel-node` everything seemed to work... and if i translated it using `babel` it also worked in plain `node`
Jest has Babel transformation built in and my Webpack config is set up to use Babel as well.

**Closed by phueper** 2017-02-21 11:30 UTC
Labels: bug

**Comment by phueper** [comment] 2017-02-21 11:32
> Jest has Babel transformation built in and my Webpack config is set up to use Babel as well.

yes, but babel will probably not translate files from the node_modules directory by default (see https://github.com/cloverfield-tools/universal-react-boilerplate/issues/41)
